version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    expose:
      - "3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
